spring:
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  mvc:
    problemdetails:
      enabled: true

logging:
  level:
    org:
      springframework:
        security: trace
