CREATE TABLE post
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title      VARCHAR(50)                             NOT NULL,
    content    VARCHAR(1000)                           NOT NULL,
    is_deleted BOOLEAN                                 NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE comment
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content    VARCHAR(255)                            NOT NULL,
    post_id    BIGINT,
    is_deleted BOOLEAN                                 NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT FK_COMMENT_ON_POST FOREIGN KEY (post_id) REFERENCES post (id)
);
