###
POST http://localhost:8080/posts
Content-Type: application/json

{
  "title": "title1",
  "content": "content1"
}

###
DELETE http://localhost:8080/posts/1

###
PUT http://localhost:8080/posts/1
Content-Type: application/json

{
  "title": "modifiedTitle",
  "content": "modifiedContent"
}
